# Generated by Django 5.0.4 on 2024-05-06 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='check_in_time',
            field=models.DateTimeField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='check_out_time',
            field=models.DateTimeField(max_length=255, null=True),
        ),
    ]
