# Generated by Django 5.0.6 on 2024-05-27 13:52

from django.db import migrations
from django.contrib.auth.hashers import make_password

def load_initial_data(apps, schema_editor):
    # get our model
    # get_model(appname, modelname)
    user_model = apps.get_model('User', 'User')
    user_model.objects.create (
        name = "Super Admin", email = "admin@gmail.com", password = make_password("admin"), role="super-admin"
        )

class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_initial_data)
    ]
